# See: http://about.travis-ci.org/docs/user/build-configuration/

language: php
php:
  - 5.3

before_script:
  - cp conf/twgit-dist.sh conf/twgit.sh
script: phpunit --configuration conf/phpunit-dist.xml
after_script:
  - /bin/bash tests/inc/codeCoverage.sh

notifications:
  on_success: always
  on_failure: always